using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


public static class CAErrorCodes
{

    // Define the error messages table
    public static Dictionary<int, (string, string, string)> ErrorMessages { get; } = new Dictionary<int, (string, string, string)>
            {
            { 200, ("Communication Port Error", "Communication Port Error", "") },
            { 201, ("--invalid timeout specified", "Check device", "The specified timeout was invalid.") },
            { 207, ("--Serial open", "Check device", "The communication port is already open.") },
            { 208, ("--Set status error.", "Check device", "Failed to configure the communication port.") },
            { 209, ("--Get status error.", "Check device", "Failed to get the communication port.") },
            { 210, ("--Usb written.", "Check device", "USB written error") },
            { 211, ("--Serial written.", "Check device", "Failed to send data to the device.") },
            { 212, ("--Serial already closed.", "Check device", "The communication port is already closed.") },
            { 214, ("--Serial read.", "Check device", "Serial read error.") },
            { 215, ("--Serial read timeout.", "Check device", "Timed out when receiving data from the device.") },
            { 299, ("--Hardware inconsistent with parameters.", "Check context", "The hardware and parameter settings are not consistent.") },
            { 300, ("Ethernet port error.", "Ethernet port error", "") },
            { 301, ("--Failed to connect via ethernet.", "Check device", "Failed to connect to the device.") },
            { 302, ("--Failed to disconnect via ethernet.", "Check device", "Failed to disconnect the device.") },
            { 303, ("--Failed to set up ethernet port.", "Check device", "Failed to set the Ethernet settings.") },
            { 304, ("--Ethernet port already closed.", "Check device", "The port was closed when performing Ethernet communication.") },
            { 305, ("--Failed to send command.", "Check device", "Failed to send data over Ethernet communication.") },
            { 306, ("--Failed to read response.", "Check device", "Failed to receive data over Ethernet communication.") },
            { 307, ("Timeout error.", "Check device", "Timed out when receiving data over Ethernet communication.") },
            { 400, ("SDK command error.", "SDK command error", "") },
            { 401, ("--Cannot execute now.", "Check context", "This command is invalid and cannot be used.") },
            { 402, ("--Invalid argument.", "Check value", "Invalid argument.") },
            { 403, ("--Duplication of name or ID, etc.", "Check context", "Duplicate ID or other information.") },
            { 404, ("--SDK has problem.", "Restart SDK", "A problem has occurred in the SDK program. Restart the SDK/application and cycle the power to the measurement instruments. Contact Konica Minolta if the problem is not resolved.") },
            { 405, ("--API failure.", "Restart Program", "SDK internal API execution error.") },
            { 406, ("--Cannot open cal_data_file.", "Check file name", "Failed to open the calibration data file.") },
            { 407, ("--Invalid CA number.", "Check value", "Invalid CA ID number.") },
            { 408, ("--Invalid RS/USB ID.", "Check value", "An invalid communication port was specified.") },
            { 409, ("--Invalid baud rate.", "Check value", "An invalid baud rate was specified.") },
            { 410, ("--Null pointer.", "Check program", "Invalid pointer argument.") },
            { 411, ("--Probe1 should be connected.", "Check argument", "Probe1 is not connected.") },
            { 412, ("--Probe not connected.", "Check program", "The specified probe is not connected.") },
            { 413, ("", "Check value", "The x/y values are invalid.") },
            { 414, ("--Invalid Lv.", "Check value", "The Lv value is invalid.") },
            { 415, ("--Invalid clr.", "Check value", "The specified color value is invalid.") },
            { 416, ("--Invalid index.", "Check value", "The specified index value is invalid.") },
            { 417, ("--Invalid CA ID.", "Check ID", "The specified CA ID value is invalid.") },
            { 418, ("--Invalid memory channel number.", "Check value", "The calibration channel number value is invalid.") },
            { 419, ("--Invalid memory channel ID.", "Check value", "The calibration channel ID value is invalid.") },
            { 420, ("--ID is too long (>10).", "Check value", "The calibration channel ID string is too long.") },
            { 421, ("--Invalid probe number.", "Check value", "The specified probe number value is invalid.") },
            { 422, ("--Invalid Probe ID.", "Check value", "The specified probe ID value is invalid.") },
            { 423, ("--Data value is too low.", "Check value", "The data value is too low.") },
            { 424, ("--Data value is too high.", "Check value", "The data value is too high.") },
            { 425, ("--Nonexistent object.", "Check program", "A non-existent object reference was passed to the method.") },
            { 426, ("--Measurement fail.", "Check probe/display setting", "A probe failed in its measurement. The display settings were out of measurement range. An external synchronization signal was not input.") },
            { 427, ("--Port already used.", "Check PortID", "The communication port is already being used.") },
            { 428, ("--Cannot cal channel 0.", "Check program", "Calibration channel 0 cannot be calibrated.") },
            { 429, ("--No output probes have been specified.", "Check program", "The output probe was not specified.") },
            { 430, ("--Insufficient buffer.", "Check program", "The buffer size for the output parameters is not sufficient.") },
            { 431, ("--Invalid memory channel comment.", "Check value or length", "An invalid calibration channel or comment was specified.") },
            { 432, ("--Invalid sampling frequency and count combination.", "Check program", "The combination of sampling frequency and number of samples is invalid.") },
            { 433, ("--Command valid for body type only.", "Check device", "A function was used that can only be used on the CA-410 data processor.") },
            { 434, ("--Invalid config type or config type combination.", "Check value", "The configuration that was created in advance and the attempted configuration are not compatible.") },
            { 435, ("--Saving was cancelled by user.", "Check device", "The user canceled saving CA-410 data processor log data to a CSV file.") },
            { 436, ("--Measurement in progress.", "Check probe", "Measurement ongoing.") },
            { 437, ("--Device not found.", "Check device", "Device not found.") },
            { 438, ("--Data not found.", "Check device", "Data not found.") },
            { 439, ("--This device cannot be connected.", "Check device type", "This device cannot be connected.") },
            { 440, ("--Command valid for probe type only.", "Check context", "Invalid command for data processor.") },
            { 441, ("--The operation could not be completed due to incorrect hardware setup.", "Check hardware setup", "The operation could not be completed due to incorrect hardware setup.") },
            { 442, ("--Invalid argument for current Display Mode.", "Check setting", "Invalid argument for current Display Mode.") },
            { 443, ("--User data was not set.", "Check program", "User data of Weighting factor was not set.") },
            { 444, ("--Incorrect device.", "Check program", "This probe is incorrect.") },
            { 445, ("--The frequency is out of range.", "Consider the obtained frequency", "The detected frequency is outside the specifications.") },
            { 500, ("CA command error.", "CA command error", "") },
            { 503, ("--Unacceptable calibration data.", "Check value", "The specified calibration data is invalid.") },
            { 504, ("--Unacceptable analog range data.", "Check value", "The specified analog display value is invalid.") },
            { 505, ("--Shortage of input values.", "Retry the setting", "Shortage of input values for calibration.") },
            { 506, ("--RGB+W matrix calibration error.", "Check calibration data", "RGB+W matrix calibration value error (the calibration data is invalid).") },
            { 510, ("--Invalid command.", "Check program", "An invalid command was specified. The CA-410 data processor is not set to remote mode.") },
            { 515, ("--Hold error", "Reset hold_mode", "Hold error.") },
            { 516, ("--Invalid memory data.", "Check data file", "Invalid calibration (memory) data.") },
            { 517, ("--Invalid memory data.", "Check data file", "Invalid calibration (memory) data.") },
            { 518, ("--Invalid memory data.", "Check data file", "Invalid calibration (memory) data.") },
            { 519, ("--Invalid memory data.", "Check data file", "Invalid calibration (memory) data.") },
            { 520, ("--No sync_signal.", "Input an external synchronization signal", "An external synchronization signalwas not input.") },
            { 521, ("--0-cal error: Failed to shade.", "Retry 0-cal", "Not dark during zero calibration.") },
            { 522, ("--Data value is too high.", "Set a color within CA's measuring range", "Outside measurement range.") },
            { 523, ("--Data value is too low.", "Perform zero_calibration", "Zero calibration required.") },
            { 524, ("--Failed to calculate color temp.", "Retry the measurement", "Outside measurement range in Tcp, duv mode.") },
            { 531, ("", "Reconnect the probe", "Failed when reading or writing memory. Restart the SDK/application and cycle the power to the measurement instruments.") },
            { 532, ("", "Reconnect the probe", "Failed when reading or writing memory. Restart the SDK/application and cycle the power to the measurement instruments.") },
            { 550, ("--FMA Flicker Value is out of range.", "", "The flicker value (contrast method) is outside the measurement range.") },
            { 551, ("--Sync Freq of FMA Flicker is invalid.", "Check the setting", "VSYNC has exceeded 130 Hz in flicker mode.") },
            { 552, ("--Flicker Meas brightness is too low.", "Lv is under the range that can be measured in flicker mode", "") },
            { 553, ("--Flicker error.", "Check probe type", "This probe type cannot perform flicker measurements.") },
            { 599, ("--System error.", "Restart application and device", "Connection or communication error. Restart the SDK/application and cycle the power to the measurement instruments.") }

            };
}
